- browse/controllers/abs_page/__init__.py
- browse/services/search/search_authors.py
- browse/templates/abs/author_links.html
- tests/data/abs_files/ftp/arxiv/papers/1411/1411.4413.abs
- tests/test_browse.py
- tests/test_search_authors.py
https://culibrary.atlassian.net/browse/ARXIVNG-924
> Collapse display of large author lists

- .gitignore
- Pipfile
- Pipfile.lock
- browse/controllers/abs_page/__init__.py
- browse/domain/identifier.py
- browse/domain/license.py
- browse/domain/metadata.py
- browse/exceptions.py
- browse/routes/ui.py
- browse/services/database/__init__.py
- browse/services/document/author_affil.py
- browse/services/document/cache.py
- browse/services/document/metadata.py
- browse/services/search/search_authors.py
- browse/services/util/external_refs_cits.py
- browse/services/util/formats.py
- browse/services/util/metatags.py
- default.nix
- mypy.ini
- tests/test_abs_parser.py
- tests/test_author_affil.py
- tests/test_metadata_tags.py
- tests/test_search_authors.py
- tests/test_typings.py
The lack of local feedback during development has resulted in an accumulation of type errors. I've fixed the existing type errors in the browse module proper, and reinstated a version of the old test script.
As previously discussed, we decided to not put an emphasis on types in test code, but we have nearly 150 errors there - I've capped it arbitrarily at 150 in the test script. However, any errors are still spit out.
We can discuss how to best get feeback by perhaps changing the `MyPyTest` class to suit our needs.
> Type improvements and related logic fixes

- Pipfile
- Pipfile.lock
- browse/domain/metadata.py
- browse/templates/abs/abs.html
- tests/test_abs_parser.py
- tests/test_browse.py
Abs page categories now uses canonical (for just the primary).
Also adds HTML tests.
https://culibrary.atlassian.net/browse/ARXIVNG-605
> Adds canonical categories

- browse/domain/category.py
- browse/domain/metadata.py
- browse/services/document/metadata.py
- browse/templates/abs/abs.html
- tests/legacy_comparison/abs_page_comparison.py
- tests/test_categories.py
https://culibrary.atlassian.net/browse/ARXIVNG-605
> Ensure correct canonical / non-canonical category display ARXIVNG-605

- browse/templates/abs/extra_services.html
- tests/legacy_comparison/html_comparisons.py
I need this merged to develop because I'm making some changes in the same code and it will be a bear to merge. (extra_services.html)
> Fixing action button on prev.

- browse/templates/abs/extra_services.html
- tests/legacy_comparison/abs_page_comparison.py
I tried to better pair the opening and closing spans.
https://culibrary.atlassian.net/browse/ARXIVNG-1228
> Fixing spans in abs page browse.

- browse/controllers/abs_page/__init__.py
- browse/domain/metadata.py
- browse/services/document/metadata.py
- browse/templates/abs/abs.html
- browse/templates/abs/extra_services.html
- tests/data/abs_files/ftp/cond-mat/papers/9805/9805021.abs
- tests/data/abs_files/ftp/cs/papers/0006/0006007.abs
- tests/data/abs_files/orig/cond-mat/papers/9805/9805021v1.abs
- tests/test_browse.py
- tests/test_formats.py
* fixes a bug where _get_source_path was only returning a path for the latest version of a paper
* add `is_latest_version` flag to DocMetadata domain class
* add `requested_id` to controller response, with tests
> ARXIVNG-1247 - Other formats should not be shown after postscript

- browse/templates/abs/abs.html
- browse/templates/base.html
- browse/templates/feedback_collector_js.html
This is a quick first-stab at adding feedback collection to browse via the footer. My thinking here was "I want feedback collection but I don't want it to be in your face." That said, I welcome any suggestions for changes!
> Feedback collector

- browse/templates/base.html
Shortly after this is deployed, I plan on switching the css link to the one on static.arxiv.org both here and in the classic code for consistency's sake.
> Header footer rebrand

- .gitignore
- browse/controllers/list_page/__init__.py
- browse/domain/listing.py
- browse/services/listing/__init__.py
- browse/services/listing/fake_listings.py
- tests/test_list_page.py
The controller passes the If-Modified-Since value to the listing service and returns a 304 if the service response indicating that the listing hasn't changed.
> Adding If-Modified-Since handling to the list controller.

- Pipfile
- Pipfile.lock
- browse/controllers/abs_page/__init__.py
- browse/domain/category.py
- browse/domain/identifier.py
- browse/domain/metadata.py
- browse/services/document/metadata.py
- browse/templates/abs/abs.html
- browse/templates/base.html
- browse/util/id_patterns.py
This is intended to be deployed with docs changes.
> ARXIVNG-1705: Hotfix to update footer

- Pipfile
- Pipfile.lock
- browse/templates/base.html
This implementation only affects browse pages (front, list, category, abs, etc).
Will have a separate implementation for NG-base shortly.
Note: right now the list and front pages don't have the extra space. I chose to not mess with it for now due to other possible layout complications.
> ARXIVNG-1918 add four column footer

- browse/controllers/cookies.py
- browse/routes/ui.py
- browse/templates/cookies.html
- tests/test_cookies.py
Reimplement the /cookies page.
https://arxiv-org.atlassian.net/browse/ARXIVNG-1427
> Reimplement the /cookies page

- browse/services/database/__init__.py
I concede, this is clearer :-)
> ditch baked query

- browse/templates/home/news.html
> News item for network maintenance

- browse/templates/home/news.html
- browse/templates/user_banner.html
> ARXIVNG-2229: Add news item and user banner message for submission system downtime

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- DECISIONS.md
- browse/templates/abs/abs.html
- browse/templates/home/news.html
- browse/templates/user_banner.html
ARXIVNG-1985 - show full proxy name under certain circumstances
Also includes news/banner updates and issue template markdown for github/jira integration.
> Pre-release merge for v0.2.4

- browse/static/css/arXiv.css
- browse/templates/base.html
accessibility edits to cornell logo and page landmarks in base template and css. No perceivable visual changes have been made, only for screen readers.
> ARXIVNG-2759 accessibility edits

- browse/static/css/arXiv.css
Fewer lines than I thought needed rolling back... but I'll take a fresh look in the morning to make sure I didnt miss anything.
> roll back bolding of links

- browse/static/css/arXiv.css
Minor css. Adding back one missing bold link, and slight adjustment to list page font size to match live styles
> minor css edits

- browse/static/css/arXiv-print.css
- browse/templates/base.html
minor change: added print style sheet to clean up printing of abs pages.
> ARXIVNG-2742 add print style sheet for abs pages

- browse/config.py
- browse/static/css/arXiv.css
- browse/templates/abs/abs.html
- browse/templates/abs/extra_services.html
- browse/templates/base.html
mobile friendly abs page edits are ready for deployment on dev or beta, whichever is best for wider user testing.
> ARXIVNG-2779 mobile friendly abs page

- browse/static/css/arXiv.css
fixes horizontal spacing of cornell logo on mobile devices.
> minor edit

- browse/templates/home/news.html
> Add news item for 2020 update and roadmap

- browse/templates/home/home.html
("14" is just from running the app locally)
Edit: removed screenshot because it no longer reflects commits
> ARXIVNG-2862: update tagline on homepage

- browse/static/css/arXiv.css
- browse/templates/stats/today.html
- browse/templates/tb/404.html
- browse/templates/tb/tb.html
- tests/test_browse.py
minor edits to fix testing errors on the trackback pages. Also includes minor style edits.
> ARXIVNG-3025 fixes last test errors

- browse/controllers/abs_page/__init__.py
- browse/templates/abs/abs.html
- browse/templates/base.html
- browse/templates/home/home.html
- browse/templates/home/news.html
- tests/data/abs_files/ftp/arxiv/papers/2004/2004.05256.abs
- tests/data/abs_files/ftp/arxiv/papers/2004/2004.08990.abs
- tests/data/abs_files/ftp/arxiv/papers/2004/2004.09471.abs
- tests/test_browse.py
Only display the COVID-19 message if the article title or abstract match one of the terms.
> ARXIVNG-3148: check paper metadata for COVID-19

- browse/templates/home/home.html
Minor edit to remove the link to the demographic survey from the homepage. The survey closes today May 11th.
> removes link to survey

- browse/templates/base.html
> Adding pendo code to browse template (#159)

- browse/static/css/arXiv.css
- browse/templates/base.html
- browse/templates/home/news.html
This branch adds a second banner to the homepage next to the covid block for #strike4blacklives. The two blocks stack to one column on narrower screen widths.
> ARXIVNG-3272

- browse/config.py
- browse/static/css/arXiv.css
- browse/templates/base.html
- browse/templates/category_taxonomy.html
- browse/templates/feedback_collector.html
- browse/templates/feedback_collector_js.html
<h2>    Bug
</h2>
<ul>
<li>[<a href='https://arxiv-org.atlassian.net/browse/ARXIVNG-3293'>ARXIVNG-3293</a>] -         fix &quot;floaty&quot; footer
</li>
</ul>
<h2>        Task
</h2>
<ul>
<li>[<a href='https://arxiv-org.atlassian.net/browse/ARXIVNG-3156'>ARXIVNG-3156</a>] -         Change category taxonomy layout to emphasize key
</li>
</ul>
> Pre-release merge for browse v0.3.1

- browse/templates/abs/abs.html
- tests/test_browse.py
simple, one line change on the abs page to restore the styling of the covid message
> fix covid message style

- browse/static/js/paperwithcode.js
Avoid xss injection capabilities by escaping everything coming from the api
> Papers With Code labs

- Dockerfile
- README.md
- bin/start_browse.sh
- uwsgi.ini
This PR represents a simple dockerization of the browse app using the arxiv/base image and uwsgi.
> ARXIVNG-3751: dockerize browse

- browse/static/js/connectedpapers.css
- browse/static/js/connectedpapers.js
- browse/static/js/toggle-labs.js
- browse/templates/abs/labs_tabs.html
Added connected papers integration based on PwC integration, + functional "off" switch
> Add connected papers integration

- browse/static/js/connectedpapers.css
- browse/static/js/connectedpapers.js
Hi,
During testing we detected a minor bug in our hover effect on some displays and also a misalignment between our css and yours for the threshold of switching between desktop and mobile versions, fixed both
> Connected papers - fix minor css bugs

- browse/templates/stats/main.html
This minor commit updates the stat links for "Institutional Downloads" and for "Submission by subject" on stat/main to the latest 2020 reports.
> minor: update stats links

- deploy/add-browse-paths.sh
- deploy/config.sh
- deploy/env_values.txt.example
- deploy/phoenix-lb-http.yaml
- deploy/setupCompute.sh
- deploy/setupLB.sh
- adds http load balancer configured to redirect to https load balancer
- minor tweaks
> Tweaks to browse GCP deployment scripts

- browse/static/js/litmaps.css
- browse/static/js/litmaps.js
- browse/static/js/toggle-labs.js
- browse/templates/abs/labs_tabs.html
Changes made to add "Open in Litmaps" functionality to abstract pages. I have tried to mirror other integrations to get the integration right.
Signed-off-by: Axton Pitt <axton@litmaps.co>
> Add “Open in Litmaps” integration to labs

- .coveragerc
- browse/config.py
- browse/pathmap.py
- browse/static/js/litmaps.css
- browse/static/js/litmaps.js
- browse/static/js/toggle-labs.js
- browse/templates/abs/abs.html
- browse/templates/abs/labs_tabs.html
- browse/templates/feedback_collector.html
- tests/test_metadata_tags.py
- adds Litmaps to arXiv Labs
- fixes tests
- add `twitter:card` meta tag to finally support twitter cards
Integration is staged on beta: https://beta.arxiv.org/abs/2007.13744
> Pre-release merge for browse v0.3.2.7

- Dockerfile
- README.md
Basic new dockerfile for phoenix.
> New dockerfile for phoenix

- browse/static/js/paperswithcode.js
- browse/static/js/toggle-labs.js
Escape datasets names on `Code & Data` labs tab.
> Dataset name formatting on PwC tab

- browse/static/js/litmaps.js
Signed-off-by: Axton Pitt <axton@litmaps.co>
> Add URI encoding for Litmaps URL

- browse/templates/stats/monthly_downloads.html
- browse/templates/stats/monthly_submissions.html
Adds new logo to monthly_submissions and monthly_downloads
> adds new logo to more stat pages

- browse/static/css/tooltip.css
- browse/templates/abs/abs.html
> hotfix for tooltip alignment issue

- browse/config.py
- browse/static/css/arXiv.css
- browse/static/js/replicate.js
- browse/static/js/toggle-labs.js
- browse/templates/abs/abs.html
- browse/templates/abs/extra_services.html
- browse/templates/abs/labs_tabs.html
- Adds Replicate integration for arXiv Labs
- Adds meta tag for DataCite DOI
- Changes linking to Google Scholar
> Pre-release merge for browse v0.3.4

- browse/static/js/iarxiv.js
- browse/static/js/toggle-labs.js
- browse/templates/abs/labs_tabs.html
Here's a branch for the IArxiv labs updates.
> ARXIVNG-4916-iarxiv

- browse/static/css/arXiv.css
- browse/static/js/iarxiv.js
Minor change to make the IArxiv link when toggled on more prominent. Also edited the text description per Ezequiel's recommendation.
> more prominent IArxiv link

- browse/config.py
- browse/templates/home/news.html
- browse/templates/user_banner.html
Added a news article to the homepage and updated the giving banner for Giving Week.
Pending: final giving week links, and testing.
> giving week messages

- browse/static/css/arXiv.css
- browse/static/js/iarxiv.js
- browse/static/js/toggle-labs.js
- browse/templates/abs/labs_tabs.html
- browse/templates/home/news.html
- browse/templates/user_banner.html
This is the giving week banner and template.
The IArxiv code is included, with a minor change: the labs-tabs button is disabled now for all subject categories.
> Giving week and IArxiv prep

- browse/templates/user_banner.html
> ARXIVNG-5229: giving-week-banner

- browse/templates/abs/labs_tabs.html
- browse/templates/user_banner.html
Same as the PR into dev:
https://github.com/arXiv/arxiv-browse/pull/284
> ARXIVNG-5230: enable cs.LG for iarxiv

- browse/templates/abs/labs_tabs.html
Add cond-mat to the array of subject categories where the iarxiv labs plugin will be enabled.
> ARXIVNG-5240: add cond-mat to iarxiv

- browse/templates/abs/labs_tabs.html
Changes to startswith cond-mat
> ARXIVNG-5240: add cond-mat to iarxiv 2

- browse/templates/abs/labs_tabs.html
Same as: https://github.com/arXiv/arxiv-browse/pull/294
> ARXIVNG-5265: banner and news link to BPS

- browse/templates/home/home.html
Adds a message about the SFS maintenance. I plan to put this up ASAP.
> Message about Nov 14th SFS maintenance

- browse/static/js/litmaps.js
Labs integration is currently broken as our api domain has changed.
> Update litmaps domain to .com

- Pipfile
- README.md
- browse/routes/ui.py
- browse/services/database/__init__.py
- browse/templates/base.html
Create endpoint for looking up member institutions by ip address.
If found, cache for 30 days or until browser closes.
If not previously cached, and db is down, user won't see member acknowledgement until db is restored, but abs page will work if .abs file can be read from nfs.
Bots probably won't execute js, so may reduce number of queries.
> ARXIVNG-5256: institutional-banner

- browse/config.py
- browse/routes/ui.py
- browse/templates/base.html
Disable geoip and remove analytics demos.
ie: 
arxiv.matomo.cloud
arxivcu.containers.piwik.pro
> ARXIVNG-5256: remove pendo code

- README.md
- browse/config.py
- browse/templates/base.html
- browse/templates/user_banner.html
Changes the user banner so all of the control of the user banner lives in the `user_banner.html` file. 
Note this is a stacked PR that merges to `forum-banner` not to `develop`.
> User banner fix

- README.md
- browse/config.py
- browse/templates/base.html
- browse/templates/home/special-message.html
- browse/templates/user_banner.html
This PR includes edits to the banner and the home page with the forum invitation content. 
The banner in user_banner.html should run for 1 week from it's deploy date.
> banner with Forum invitation

- browse/templates/user_banner.html
I tried to improve the instructions and comment out with Jinja comment instead of HTML ones.
> User banner fix part 2

- browse/templates/home/home.html
- browse/templates/home/special-message.html
- browse/templates/user_banner.html
This small PR updates:
- the text about the forum on the homepage
- updates the forum banner text for later use (but not deploying now)
- and removes the "robots beware" text from the homepage
> update forum messages

- browse/templates/home/special-message.html
- browse/templates/user_banner.html
This PR updates the content and dates of the homepage message and the header banner. 
The banner is set to display starting tomorrow, and ending the day of the forum.
> Forum updates

- browse/templates/abs/labs_tabs.html
Minor edit to labs tabs text that changes 'flowers' to singular 'flower'.
> change influence flower name to singular

- Pipfile
- Pipfile.lock
- browse/controllers/abs_page/__init__.py
- browse/pathmap.py
- browse/routes/ui.py
- browse/services/document/metadata.py
- browse/services/util/formats.py
- browse/static/css/arXiv.css
- browse/templates/abs/abs.html
- browse/templates/abs/extra_services.html
- tests/data/abs_files/orig/arxiv/papers/0704/0704.0615v1.abs
- tests/data/abs_files/orig/arxiv/papers/0704/0704.0615v2.abs
- tests/data/abs_files/orig/arxiv/papers/0704/0704.0615v3.abs
- tests/data/abs_files/orig/arxiv/papers/0704/0704.0615v4.abs
- tests/test_browse.py
Changes for the "display withdrawal status on abs page more prominently" ticket.
https://arxiv-org.atlassian.net/browse/ARXIVNG-1851
If I should add anyone else as a reviewer, please let me know.
> ARXIVNG-1851

- browse/templates/stats/main.html
Update this year's urls on: https://arxiv.org/stats/main
> ARXIVCE-334: update this years public institution stats

- browse/templates/home/special-message.html
This is a minor text change. Here is a quick screenshot:
> add 'all news' link to homepage black news box

- browse/config.py
- browse/templates/base.html
- browse/templates/home/special-message.html
- browse/templates/user_banner.html
for the user about being in gcp.
> ARXIVCE-742: 3 locations where we could put a message

- script/sync_prod_to_gcp/sync_published_to_gcp.py
Removes bug in debugging statement.
> Fixes a bug in sync.

- browse/services/documents/db_implementation/db_abs.py
David F. and I worked on this together. ARXIVCE-712
> Fixes bug with ancilary file listing not showing up on abs page

- browse/templates/user_banner.html
- tests/test_fmt_txt.py
One line change: adds a link to donate.js on the user_banner.html page.
This needs to be tested.
> adds donate.js

- browse/domain/fileformat.py
- browse/routes/dissemination.py
- browse/services/dissemination/article_store.py
- browse/services/dissemination/source_store.py
heres a way to get source files for native html docs with just the identifier
> Html route access native html

- browse/config.py
- browse/controllers/files/ancillary_files.py
- browse/controllers/files/dissemination.py
- browse/services/dissemination/article_store.py
- browse/services/key_patterns.py
- browse/stream/file_processing.py
- browse/templates/list/author.html
- browse/templates/list/new.html
- tests/dissemination/test_unavailable.py
- tests/test_browse.py
> Arxivece 274 fix test cases latexml

- script/sync_prod_to_gcp/sync_published.sh
- script/sync_prod_to_gcp/sync_published_to_gcp.py
(1) Added the changes left on arxiv-sync
(2) PID file got not made with permission error as /var/run is not writable by e-prints
> sync to gcp 2023 11 06 update

- browse/static/js/toggle-labs.js
- browse/static/js/txyz.js
- browse/templates/abs/labs_tabs.html
Add txyz ai integration based on connected papers integration https://github.com/arXiv/arxiv-browse/pull/202
> Add txyz ai integration

- browse/controllers/abs_page.py
- browse/domain/identifier.py
- tests/conftest.py
- tests/test_browse.py
See https://arxiv-org.atlassian.net/browse/ARXIVCE-1088
Minor protection against strange paper IDs.
> 404 response for funny paper id to /abs ARXIVCE-1088

- browse/controllers/abs_page.py
- browse/controllers/home_page.py
- tests/test_304.py
- tests/test_browse.py
- tests/test_db_abs.py
As requested by admin team to allow smoother support.
> Set abs page cache-control to 1h

- browse/controllers/files/__init__.py
- browse/controllers/files/dissemination.py
- browse/routes/dissemination.py
- browse/routes/src.py
- tests/data/classic_scholar_metadata_tags.json
- tests/dissemination/test_newids.py
- tests/dissemination/test_no_source.py
- tests/dissemination/test_oldids.py
- tests/dissemination/test_redirect.py
- tests/dissemination/test_unavailable.py
- tests/test_browse.py
- tests/test_html_postprocess.py
Adds canonical "Link" header to /pdf
It will be a url like 
https://arxiv.org/pdf/2401.12345
or
https://arxiv.org/pdf/2401.12345v3
https://arxiv-org.atlassian.net/browse/ARXIVCE-63
> Adds canonical to /pdf

- browse/controllers/abs_page.py
- browse/controllers/response_headers.py
- browse/domain/identifier.py
- tests/test_304.py
- tests/test_db_abs.py
This reverts commit 41a58bef1eb4304fb4fd89b387a75dbddc564908.
This caused problems in production.
> Revert "Changing to using last-modified to etag on /abs arxivce-1247"

- browse/templates/400.html
this template is the default for user requests that are incorrect in some way
> reworded 400 response to make sense for bad request

- script/sync_prod_to_gcp/subscribe_submissions.py
- script/sync_prod_to_gcp/test/test_subscribe_submissions.py
Support the old arxiv ID and write test for it.
> [ArxivCE-1316] Support old submissions

- browse/routes/ui.py
- tests/test_browse.py
- tests/test_tb_page.py
> Fixes problem with /tb page where it would 500 with bad data

- browse/services/dissemination/source_store.py
- tests/dissemination/test_integration.py
Fixes bug where /src would return same source file for all versions of a paper.
> Fixes bug with /src versions ARXIVCE-1455

- Dockerfile
Increasing number of worker in docker file.
> Increase Dockerfile gunicorn workers from 1 to 4

- Dockerfile
also deploys slight homepage reformatting
> decrease listings max to 1000

- browse/controllers/stats_page.py
- tests/test_stats_page.py
> ARXIVCE-1623: show fastly counts and not cit web vms

- script/sync_prod_to_gcp/sync_published_to_gcp.py
An error in the logs indicates that this should be a tuple but it really needs the list to be unpacked as function arguments.
> Types to retry.if_exception_type needs list to be unpacked

- browse/formatting/cite.py
- tests/test_cite.py
The `Category` that populates the primaryClass use to subclass `str` but that was changed. That caused this regressio
> Fixes bibtex primary class

- browse/formatting/cite.py
There's a comma missing, which causes the bibtex output to not validate correctly.
> added missing comma, fixes DOI formatting

- browse/controllers/archive_page/__init__.py
- browse/controllers/files/__init__.py
- browse/controllers/files/ancillary_files.py
- browse/controllers/files/dissemination.py
- browse/controllers/home_page.py
- tests/dissemination/test_no_source.py
- tests/test_archive.py
- tests/test_db_abs.py
switch to using Surrogate-Control header for caching. This header will apply just to fastly and nothing else
> Arxivce 2400 caching just for cdn

- poetry.lock
- pyproject.toml
- script/sync_prod_to_gcp/requirements.txt
- tests/test_latexml_graceful.py
This PR will require cloud run config changes before it is merged.
ARXIVCE-2433
> merge the latexml db graceful change to master 

- browse/static/css/ar5iv.0.7.9.min.css
the font shows up if you use this version of the name ¯\_(ツ)_/¯
> change math stix font name

- browse/templates/user_banner.html
Also removes some accessibility forum banners
> Adds db outage banner

- browse/templates/user_banner.html
> outage banner back to normal

- browse/templates/abs/abs.html
- tests/test_db_abs.py
adjust cannonical link to have domain name
> add meta description

- browse/templates/abs/abs.html
- browse/templates/user_banner.html
- tests/test_db_abs.py
Also adds meta tag for description to abs page.
> Deploy removal of banner.

- browse/config.py
- browse/controllers/abs_page.py
- browse/controllers/files/__init__.py
- browse/controllers/files/ancillary_files.py
- tests/dissemination/test_encrypted.py
- tests/dissemination/test_no_source.py
- tests/dissemination/test_unavailable.py
- tests/test_html.py
- tests/test_src.py
Sets the Surrogate-Control maxage to one year. Surrogate-Control sets only the fastly (or similar) caching.
> Cache maxage set to 1 year ARXIVCE-2719

- browse/templates/abs/abs.html
Just getting the latest JS asset to load.
> Fresh toggle-labs.js script as of today

- browse/config.py
- browse/services/dissemination/__init__.py
- browse/services/dissemination/article_store.py
- browse/services/global_object_store/__init__.py
Need ability to configure the reasons.json file. 
ARXIVCE-2772
> Add config for reasons file path

- browse/static/css/slider.css
- browse/static/js/donate.js
- browse/templates/user_banner.html
deploy arxiv privacy policy banner to run from December 12 to dec 31
mobile:
desktop:
> Arxivce 2879 privacy policy banner

- browse/templates/cookies.html
Cleans up some debug text that is no longer helpful.
> [minor] No longer editing cookies at /cookies

- browse/templates/user_banner.html
> remove close option that is not i understand.

- browse/templates/base.html
adds annual survey to desktop banner 1/16 - 2/4
> ARXIVCE 3006 annual survey banner

- browse/services/audio.py
- browse/static/css/abs_audio.css
- browse/static/css/arXiv.css
- browse/templates/abs/extra_services.html
- browse/templates/audio_landing_page.html
- tests/test_audio.py
https://arxiv-org.atlassian.net/browse/ARXIVCE-3311
Changes /abs/{paper_id} page to now have "Extra" area that will be under "Access Paper" and "Ancillary files" (see attached screenshot)
Style changes /auido/{paper_id} and adds css file. (see attached screenshot)
> Sciencecast UI changes

- browse/templates/base.html
Changes end date of minimal banner (the end date for the big banner had already passed)
> Taking down minimal job posting banner

- browse/static/css/abs_audio.css
- browse/templates/audio_landing_page.html
> ARXIVCE-3416 feedback collector on audio page

- browse/static/js/donate.js
- browse/templates/user_banner.html
keeps banner from living as long as it is cached (timezone offset is imperfect)
adds birthday banner
> parameterize banner, set birthday one

- browse/templates/user_banner.html
Reactivate the data collection (Opt In) banner.
> Reactivate opt in banner. 

- browse/static/css/arxiv-html-papers-theme-20250916.css
Simple typo, uncovered while testing in develop
> [HTML25-165] css typo --math-caligraphic-font-family

- browse/templates/user_banner.html
> ARXIVCE-3843: Delete bad blog post link.

- browse/templates/user_banner.html
Post-maintenance banner update.
> ARXIVCE-3843: Post-maintenance banner update.

- browse/templates/user_banner.html
> Banner update

- browse/templates/user_banner.html
> Fix quotes in href
