- browse/controllers/abs_page/__init__.py
- browse/domain/metadata.py
- browse/routes/ui.py
- browse/services/document/metadata.py
- tests/test_abs_parser.py
- tests/test_browse.py
- tests/test_docmetadata.py
This PR essentially covers the conversion of https://github.com/cul-it/arxiv-httpd/blob/master/cgi-bin/abs.pl#L63-L124. 
Some of these cases (like singleton parameters on /abs absent of any other path info) are fairly rare and might be candidates for removal in a future release. 
The `fmt=txt` case is supported by a new `Docmetadata` field called `raw_safe` which is the raw abs string minus the submitter email address.
Examples are demonstrated in test cases.
> ARXINVG-1038 - add support for legacy /abs request parameters

- browse/controllers/abs_page/__init__.py
- browse/domain/category.py
- browse/domain/identifier.py
- browse/templates/abs/extra_services.html
- tests/test_browse_links.py
Issue: Browse context is not always showing the canonical archive when viewing an old ID
https://culibrary.atlassian.net/browse/ARXIVNG-1262
"e.g. for physics/9707012 the archive in the browse context is "physics" per the identifier. It should be "math-ph" because the primary category is "math-ph" which is in the archive of the same name."
Added tests for new ID, old ID and old ID with canonicalized primary.
Refactored browse template macro to move most of the logic out of the template and into the controller.
> Fixes browse context for canonical archives

- browse/config.py
- browse/controllers/abs_page/__init__.py
- browse/services/database/__init__.py
This is a first stab at handling DB problems in browse more gracefully. I added an error handler as decorator  called `db_handle_operational_error` to the query functions that catches `OperationalError` and `DBAPIError` exceptions from SQLAlchemy and returns a default value; any other exception gets raised and propagated.
I also added a new config `BROWSE_DISABLE_DATABASE` that will cause any function decorated by `db_handle_operational_error` to just return the specified default value; in other words, it short-circuits the connection attempt and query.
> ARXIVNG-1275 - Handle database errors more gracefully

- browse/config.py
- browse/templates/base.html
- browse/templates/user_banner.html
This is still rudimentary, but wanted to provide a way to display the user banner in browse, specifically for the network migration CIT is doing Nov 1.
> preliminary user banner support

- browse/templates/base.html
This is all there is to it for the current browse release; I'll add the homepage footer changes to the ARXIVNG-1296 branch I'm currently working on.
> Add a11y text/link to footer

- browse/templates/abs/abs.html
We've learned from Steinn that ever since we modified the footer to include a11y information, the link previews (particularly those generated by FB) are sub-optimal. This PR is a first stab at including some of the social media meta tags per these [guidelines](https://css-tricks.com/essential-meta-tags-social-media/), which might help fix that display problem. Absent from this are the image tags that are technically required (but maybe, not really). 
I'm mainly putting this out there to continue the conversation, not necessarily to deploy something expediently (but that could be an option too).
> Add rudimentary support for social media meta tags

- browse/factory.py
- browse/filters.py
- browse/services/util/tex2utf.py
- browse/templates/abs/abs.html
- tests/data/abs_files/ftp/arxiv/papers/1901/1901.05426.abs
- tests/test_abs_parser.py
- tests/test_browse.py
- tests/test_tex2utf.py
The core of this problem is that in arxiv-browse, the abs template is using tex_2_utf on the abstract. This is converting TeX like /psi to the unicode φ. This is bad because φ doesn't look like a TeX /psi. 
This PR is step 1 and step 2 of plan B:
Step 1 In NG arxiv-browse have a new filter tex_2_utf_no_symbols
Step 2: In NG arxiv-browse, use that new filter on abstract only 
The changes to the legacy submission display are in the works.
The classic system does not do tex_2_utf, only normal HTML escaping: 
https://github.com/arXiv/arxiv-lib/blob/64ae85ad9168713198fc682ab3882cc5a3f02a21/lib/arXiv/HTML/Abstract.pm#L904
> Arxivng 1612 hotfix

- browse/templates/base.html
Super simple inline declaration to prevent overlap. It's not beautiful, but it's functional for now.
> ARXIVNG-1785 clear float on feedback to prevent footer collision

- browse/templates/abs/abs.html
- browse/templates/short_trailer.html
This fix does two things:
1) moves the lowest line out of the "left column" div so that it expands to full width
2) adjusts margin so that the two lines are aligned vertically.
Note that at very small widths the two lines are pinned to either side of the screen, this is expected behavior (see screenshot).
> ARXIVNG-1797 adjust margins to fix misalignment of feedback sentence

- browse/config.py
This is just a temporary workaround for ARXIVNG-2063 and the case where a missing route in the URL map would cause an exception to get raised in the duplicate tapir_session cookie scenario.
> Workaround for ARXIVNG-2063

- browse/routes/ui.py
- tests/test_archive.py
> ARXIVNG-2098: allow trailing slash in /archive/<archive_id/

- browse/services/search/search_authors.py
- tests/data/abs_files/ftp/arxiv/papers/1902/1902.05884.abs
- tests/legacy_comparison/abs_page_comparison.py
- tests/legacy_comparison/html_comparisons.py
- tests/test_browse.py
- tests/test_search_authors.py
/abs/1902.05884  should not have odd '0 additional authors' text.
This PR fixes that. 
Also fixes off by one bug in split_long_author_list()
Adds some changes to legacy comparison tests.
ARXIVNG-2085
> Fixes an author list display bug

- browse/templates/home/home.html
This fixes the form on the home page.
This can be tested by changing the form action in home.html from
action="/multi" to action="https://arxiv.org/multi"
so the form goes to the production arxiv.
A query parameter had the incorrect name.
ARXIVNG-2105
> Fixes NG form that goes to legacy catchup page.

- browse/templates/abs/abs.html
- browse/templates/home/news.html
- browse/templates/user_banner.html
Some background first: 
- as of today, there are 11,270 distinct proxy names in the system
- if you remove the proxy names that start with "ccsd", you are left with 130 distinct names
- of the 11,140 proxy names that start with "ccsd", the names generally look like this (where `N` is an integer):
`ccsd ujm-NNNNNNNN`
`ccsd hal-NNNNNNNN`
`ccsd inria-NNNNNNNN`
The classic display logic simply took the first word in the proxy name and capitalized it; I think this makes sense for the CCSD case but not necessarily others. So, in this PR I'm proposing the following changes to the display logic:
- if the proxy name is only one word long OR starts with "ccsd", then upper case it
- if the proxy name is more than one word long, display it as is, with tex2utf filtering; trail with "as proxy" instead …
> ARXIVNG-1985: proxy field in Submission history should (mostly) show full text

- browse/templates/home/news.html
The plan is to deploy this on Friday, June 21, after the database / submission system maintenance is completed.
> ARXIVNG-2230: add maintenance news item

- browse/templates/user_banner.html
I updated the text and the link to the member organizations to /about/ourmembers.
> ARXIVNG-2710: Update banner text for Fall 2019 giving campaign

- browse/static/css/browse_search.css
css edits to the browse search bar to fix various browser errors and discrepancies. Could not duplicate the error shown in ticket but fixed the following:
- FF: default down arrow still displaying
- centering search form on mobile
- corrected floats and clears on mobile
>  arxivng-2231: Browse search bar bleeding in mobile view

- browse/static/css/arXiv.css
- browse/templates/abs/abs.html
- browse/templates/home/home.html
- browse/templates/list/base.html
- tests/test_browse.py
Addresses the following accessibility related edits on browse:
- fixed homepage links by adding unique aria labels.
- addressed duplicate IDs on abs.
- added secondary search form aria labelling to homepage.
Please note the changes to the abs page are dependent on a very small PR for base (single line edit made to templates/base/macros.html)
> ARXIVNG-2758 various accessible edits

- browse/templates/abs/extra_services.html
The screenshot below shows the sidebar with a new "Additional Resources" section that contains outbound search links for Google Scholar and Semantic Scholar. Previously, the Google Scholar link was being injected by the bibex javascript in the same section with the "Export citation" link. 
My questions:
- Is "Additional Resources" the best name for this new section?
- Perhaps not germane to this PR, but what if anything should we do about the "Export citation" link that is still being injected by bibex (regardless if bibex is enabled or not). It does seem valuable, but should probably be grouped with the other bibex elements if we want a clearer separation between core arXiv functionality and arXiv Labs functionality.
Changes are staged on beta, e.g. https://beta.arxiv.org/abs/1911.11778 …
> ARXIVNG-2902: move Google and Semantic Scholar links into dedicated sidebar section

- browse/config.py
- browse/templates/abs/extra_services.html
- browse/templates/home/home.html
- browse/templates/tb/base.html
<h2>        Bug
</h2>
<ul>
<li>[<a href='https://arxiv-org.atlassian.net/browse/ARXIVNG-2867'>ARXIVNG-2867</a>] -         all /tb/[id] pages incorrectly link to the trackback help, among other issues on that page
</li>
</ul>
<h2>        New Feature
</h2>
<ul>
<li>[<a href='https://arxiv-org.atlassian.net/browse/ARXIVNG-2902'>ARXIVNG-2902</a>] -         Add Semantic Scholar link to side panel
</li>
</ul>
<h2>        Task
</h2>
<ul>
<li>[<a href='https://arxiv-org.atlassian.net/browse/ARXIVNG-2862'>ARXIVNG-2862</a>] -         Update &quot;about arXiv&quot; at top of arXiv.org &amp; what shows for &quot;New&quot;
</li>
</ul>
> Pre-release merge for browse v0.2.8

- browse/static/css/arXiv.css
- browse/templates/base.html
adds the sorry app links to footer as on the similar base branch. Also updates the accessible icon colors to match base styles.
> ads sorry app links to footer, updates accessible icon colors.

- Pipfile
- Pipfile.lock
- browse/config.py
- browse/controllers/prevnext/__init__.py
- browse/controllers/prevnext/tests.py
- browse/controllers/tb_page/tests.py
- browse/templates/tb/base.html
<h2>        Task
</h2>
<ul>
<li>[<a href='https://arxiv-org.atlassian.net/browse/ARXIVNG-2985'>ARXIVNG-2985</a>] -         add status.arxiv.org link to arXiv page templates
</li>
<li>
Update dependencies, including arxiv-base
</li>
</ul>
> Pre-release merge for browse v0.2.9

- browse/static/css/arXiv.css
- browse/templates/home/home.html
- browse/templates/home/news.html
arXiv has decided that we will provide covid-19 quick search links on the home page, both to arXiv and to bioRxiv/medRxiv. 
This is a first pass (see screenshot below). @SBBCornell please reposition or restyle as needed.
> covid-19 quick search links in arXiv and bioRxiv/medRxiv

- browse/config.py
- browse/templates/base.html
I've added this so that we have maximum visibility for status alerts. Once a user clicks on the close button, they won't be bugged by it again. Example screenshot below:
> add support for status page web plugin

- browse/templates/abs/extra_services.html
- tests/test_browse_links.py
fixes desktop display of the "current browse context" and "change to browse by" sections in the right sidebar of the abstract page.
> hotfix to display of browse in sidebar

- browse/static/css/arXiv.css
- browse/templates/home/news.html
> adds homepage news: no announcement on june 9th

- browse/static/css/arXiv.css
- browse/templates/base.html
The footer on the live site is aligned to the bottom of the content so appears to float on pages with short content blocks (and happens more for users with large monitors).
These small edits align the footer to the bottom of the browser window even if the content is short. On pages with longer content there is no discernible change.
New:
Old:
> keeps footer aligned to bottom of browser even with short content

- browse/static/css/arXiv.css
- browse/templates/category_taxonomy.html
These small changes order the category taxonomy page by category key instead of category name, and visually emphasize the key. 
Per Steinn's feedback, he often doesnt know the category name and is scanning by category key in order to figure out what it is. 
Here is a screenshot for reviewing:
> minor: emphasize category key over category name

- browse/static/js/core-recommender.js
1. Removes cookie management from the `core-recommender.js`
2. Adds a conditional check for the script loading:
- if the `document` was loaded already, the `init()` function
is executed
- if the `document` was not loaded, a new 'load' listener is added
---
I checked how the arXiv Labs' switchers work and found that the cookie management is done separately. I removed this from the CORE Recommender's stript accordingly.
Also, I fixed the problem with immediate loading of the recommendations. There was a little unexpected case.
However, I see the differences between the deployed script on the `beta` and the latest version in the `develop` branch. I hope there will be no conflicts.
---
I will properly test it and turn off the draft later.
> Clean-up CORE Recommender script

- Pipfile.lock
- browse/static/css/arXiv.css
- browse/templates/tb/base.html
- browse/templates/tb/macros.html
- browse/templates/tb/recent.html
- browse/templates/tb/tb.html
- tests/test_browse.py
Some html and css edits to emphasize the trackback title more and the metadata less.
When spinning it up locally I cant find a paper that has a trackback. The attached are tested with these changes in-browser on the live site, but Id love to locate a test paper with a trackback to test with also before it is pushed live. Do you know of any?
Screenshot of the new visual changes for reference:
> trackbacks: emphasis on title

- browse/static/css/arXiv.css
- browse/templates/home/home.html
- browse/templates/home/news.html
Steinn pointed out the COVID block on the homepage could use a rethink. The two somewhat dated news items are removed and it's taking up less space in a right hand column. Also added minimal styling around the search on the left to differentiate it from the surrounding text.
Screenshot attached for quick review:
> minimizes COVID message block on homepage

- browse/templates/abs/abs.html
- browse/templates/abs/extra_services.html
No visual changes are included in this branch. It adds new unique classes to elements in the abs sidebar, and to the endorsers link in the main abs content area, so that the pendo tag manager can more precisely tag and track usage.
> adds unique classes to abs for Pendo targeting

- browse/static/css/arXiv.css
- browse/templates/home/home.html
- browse/templates/home/news.html
- browse/templates/home/special-message.html
This branch adds a news item to the homepage about the TeX live update.
This is the message that will display up until 7:55am on Oct. 1:
After that date/time passes and up until the end of Nov. the news section will display this message:
(informational aside: the original plan was to add this blurb with Pendo only but I learned that they have very limited options for inline text injection. Their guides are intended to float on top of existing content as a new layer, or be a full width badge at the top or bottom of the page. I can inject a 'badge' but it requires special css tweaks that target the unique pendo badge ID, which means pushing an edit to our servers anyway. It also launches a guide when clicked, though I can make that guide invisible, but it still feels hacky. I will …
> News item about TeX updates on homepage

- .pylintrc
- browse/controllers/abs_page/__init__.py
- browse/services/util/response_headers.py
- tests/test_304.py
This fixes etag handling and last-modified time handling.
It also gets the request headers for these in a case insensitive way.
Jim and I were hoping that this would fix people needing to refresh to get updated papers. The refresh would be intended to get around the sever returning a 304 Not-Modified. But this bug was causing the server to always 200 (Ok) and never 304 (Not modified).
> This fixes etag quotes and a couple other things

- browse/templates/abs/extra_services.html
This pulls the Google Scholar link generation into a separate macro and updates the query parameters to use those recommended by Google Scholar
before:
`https://scholar.google.com/scholar?q=Evolutionary%20games%20on%20minimally%20structured%20populations.%20arXiv%202008`
after:
`https://scholar.google.com/scholar_lookup?title=Evolutionary%20games%20on%20minimally%20structured%20populations&author=Gergely%20J%20Szollosi&author=Imre%20Derenyi&publication_date=2008/10/15&arxiv_id=0704.0357`
> ARXIVNG-3663: build Google Scholar link using recommended parameters

- browse/static/css/arXiv.css
- browse/static/js/paperswithdata.js
- browse/static/js/toggle-labs.js
- browse/templates/abs/labs_tabs.html
The code is formatted the same way as the existing code integration in `paperswithcode.js`, but is made to be entirely independent, so it can be independently turned on and off.
> Adding a "Data" tab using Papers with Code

- browse/static/css/arXiv.css
- browse/static/js/paperswithcode.js
A couple of small fixes for spacing consistency for the Code and Data sections.
> Small style fixes for the "Code & Data" tab

- browse/static/css/arXiv.css
- browse/static/js/paperswithcode.js
Small fix to use anchors because we can now how two separate calls for contribution (for code and data)
> Use anchors for calls on contribution on Code & Data tab

- browse/static/js/paperswithcode.js
Although the anchor links are more clear in call to action, we found they can be confusing for novice users. So this PR is effectively reverting #220.
> Revert #220

- browse/static/js/toggle-labs.js
I couldn't add it to the `script-url` element because it escapes `?` and didn't want to disable that.
> Add timestamp to clear cache for Papers with Code widget

- browse/templates/abs/abs.html
A small update related to #234 that I forgot to do yesterday. Bumps up toggle-labs version to force reloading of the cached script.
> Bump toggle-labs.js version

- browse/static/js/scite.css
- browse/static/js/scite.js
- browse/static/js/toggle-labs.js
- browse/templates/abs/labs_tabs.html
Add scite.ai Smart Citations badge to bibliographic tools in arXiv labs based on the approved proposal for arXiv labs.
Please note: scite.ai currently only supports publications with DOIs. Here we leverage, like the cite.js plugin the meta tag containing a DOI where it exists.
cc @mhl10
**With DOI**
**Without DOI**
> add scite.ai Smart Citations badge to  bibliographic tools in arxiv labs

- browse/templates/home/news.html
- browse/templates/user_banner.html
Adds a news item and an updated banner with a post-giving week message and donate links. See screenshot below.
@mhl10 I could not find where to set the banner start and end dates, but it should run from today through Sunday night.
> post-giving week banner and news

- browse/static/css/slider.css
- browse/templates/home/news.html
- browse/templates/user_banner.html
This PR adds a banner and homepage news link to the brand perception survey. It should run for 24 hours, from 1:00 AM on Monday the 15th to 1:00 AM on Tuesday the 16th. 
@mhl10 I used this timeblocking on the homepage news: {%- if rd_int >= 202111150100 and rd_int <= 202111160100 -%}
Screenshot of the homepage:
> Adds BPS banner and news links

- browse/routes/ui.py
- tests/test_browse.py
This fixes the problem with the bibex citation for old IDs.
> Fixes /bibtex citation for old style ids ARXIVNG-4751

- README.md
This PR updates the Docker section of the README.
Before this change, running the second command fails:
```
$ docker run -it 8000:8000 arxiv/browse:some_tag          
Unable to find image '8000:8000' locally
docker: Error response from daemon: pull access denied for 8000, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```
Summary of changes:
- Updates the second run command to include the missing `--publish` flag
- Removes the `:some_tag` suffix from the image name. It's not strictly needed and could cause confusion.
- Adds a link to the Docker download page
- Removes a code block syntax error at the bottom of the README
> Fix Docker instructions in README

- README.md
- script/start
In my recent work on #257, I noticed that I had to stop the server and run these Docker commands every time I made changes. This PR adds a start script that bundles the commands into one, which makes it a bit easier to start and stop the server.
The script is following the [Scripts to Rule Them All](https://github.com/github/scripts-to-rule-them-all) methodology popularized by GitHub.
cc @mhl10 @SBBCornell
> Add start script

- browse/templates/abs/abs.html
This will make it discoverable by Google Scholar and other
indexers. See e.g.
https://scholar.google.com/intl/it/scholar/inclusion.html#indexing
> Add a meta tag exposing an article's DOI

- browse/templates/abs/labs_tabs.html
Add the subcategories of astro-ph to the list that display the IArxiv recommender button.
The abs page was checking for "astro-ph", but should have been checking any subcategory.
> Add astro-ph subcategories

- browse/static/css/arXiv.css
- browse/templates/home/special-message.html
- browse/templates/user_banner.html
Background: Per Steinn, there may be budget and more pressure for accessibility improvements this year. We need to talk to researchers who access arXiv with assistive technologies to ensure accessibility efforts are guided by real user needs. Our existing list of users with accessibility needs has a response rate of 0%. We need to cast a wider net.
This PR temporarily adds a banner to the header, and a message on the homepage, requesting input. The link takes them to a [very brief qualtrics survey](https://cornell.ca1.qualtrics.com/jfe/form/SV_3K3qwdEH5gnzw6q?jfefe=new), I will then reach out to set up individual interviews. My goal is to build a more active feedback group, and conduct at least 8 initial interviews.
> Accessibility banner and homepage message

- browse/services/document/metadata.py
- tests/data/abs_files/ftp/arxiv/papers/2004/2004.02153.abs
- tests/test_browse.py
// at the start of a line for TeX cases was causing the abs parser to fail for https://arxiv.org/abs/2004.02153
https://arxiv.org/abs/2004.02153 works because Jake manually fixed the abs file.
This PR adds an alternative way to split the abs file to handle this case.
> Fixes 500 errors abs file due to // for TeX cases

- browse/templates/user_banner.html
This PR is for the Fall 2022 Giving Week banner. 
Devs, could you help Alison and I with two things:
- test view it on dev server
- queue the banner to go live on the morning of Monday October 24th, and stop displaying on the evening of Sunday October 30th.
> updates giving week banner

- browse/templates/home/news.html
- browse/templates/user_banner.html
This commit adds a banner with link to the survey, and a news item on the homepage with a link to the same.
The start and end date on news.html should be updated to match whatever the start and end date of the banner are, so they appear at the same time. We want to display both for a 24 hour period. It is not so important exactly what time that 24 hour period begins, but preferably on Monday or Tuesday so we match previous years. 
Could we also preview it on dev or beta ahead of time, just to make sure all is well.
> banner and news link to BPS

- browse/config.py
- browse/templates/abs/abs.html
Some of our paper's abs pages aren't searchable at google. Maybe our multiple urls look like we're trying to game the page rank.
> ARXIVCE-62: abs-canonical-url

- browse/static/css/arXiv.css
- browse/static/js/replicate.js
- browse/static/js/spaces.js
- browse/static/js/toggle-labs.js
- browse/templates/abs/abs.html
- browse/templates/abs/labs_tabs.html
This pull request introduces a new [arXiv Labs](https://labs.arxiv.org/) integration that displays links to interactive machine learning demos from [Hugging Face Spaces](https://huggingface.co/spaces). It mirrors the implementation used for Replicate AI demos.
Screenshot:
Demo:
Running the development environment. From the root of this repository, run:
- `docker build . -t arxiv/browse`
- `docker run -it --publish 8000:8000 arxiv/browse`
Once the Docker is running:
- go to any paper, e.g. `http://localhost:8000/abs/0704.0988`
- Because none of the dummy dev papers are linked to any HF model, use the "override_paper_id" URL param to override the paper_id used to search for demos, e.g. `http://localhost:8000/abs/0704.0988?override_paper_id=1810.04805` or …
> Introduce Spaces Demos

- browse/static/css/arXiv.css
- browse/static/js/spaces.js
An update to only load 5 Hugging Face Spaces demos in the Demos tab. If a user wants to view more, instead of expanding in the page, we link to the Hugging Face search. This should look cleaner and not overload the page with too much content.
Running the development environment. From the root of this repository, run:
- `./script/start`
Once the Docker is running:
- go to any paper, e.g. `http://localhost:8000/abs/0704.0988`
- Because none of the dummy dev papers are linked to any HF model, use the "override_paper_id" URL param to override the paper_id used to search for demos, e.g. `http://localhost:8000/abs/0704.0988?override_paper_id=1810.04805` or `http://localhost:8000/abs/0704.0988?override_paper_id=1912.08777 `
- ArXiv hides the demo tab unless the paper is a CS paper, which none of …
> Update Hugging Face Spaces Integration, minor aesthetic changes

- README.md
- browse/static/js/toggle-labs.js
- browse/templates/abs/labs_tabs.html
- main.py
This undoes changes in 8dc1713 which made the demo tab visible and also enabled the replicate labs items in that tab for a subset of archives. It is an arXiv policy that the labs items are opt-in. 
This also has the effect of making the Demo tab enabled for all archives and categories. Previously it was just for cs, eess and stats.
Adds missing about links for CORE and PwC.
Adds main.py for easy startup of the flask app.
> labs pages: not default enabled for the demo tab, links for CORE and PwC

- browse/static/js/sciencecast.js
- browse/templates/abs/labs_tabs.html
Rename "Code & Data" to "Code,Data,Media"
Moves science cast under that tab.
This is up on beta.arxiv.org https://beta.arxiv.org/abs/0704.0526?override_paper_id=2008.02563
**With Just ScienceCast**
**With ScienceCast and PwC/Meta**
> Changes to the labs tabs

- browse/static/js/dagshub.js
- browse/static/js/toggle-labs.js
- browse/templates/abs/labs_tabs.html
This PR introduces an integration with DagsHub. This integration shows Links for DagsHub projects that implement a paper.
The implementing repository also get an arXiv link on the top of the page on DagsHub 😄 
This is how it looks on arXiv:
> Integrate arXiv with DagsHub

- browse/templates/abs/labs_tabs.html
Replace the link "What is ScienceCast?" with the new one
> Update to ScienceCast plugin

- browse/static/js/inf-script.js
This pull request adds a summary sentence explaining the data behind the Influence Flowers. (Yellow box on the image)
e.g., "The Influence Flowers are generated from 2 matching papers (112 references and 70 citations), from academic data as of December 2021."
The summary sentence will update when the dataset changes.
> Add a description of the data behind the influence flowers

- browse/static/js/toggle-labs.js
At the moment the labs cookie expires every time the user closes the browser window (ie they are session-bound). Because of this I find myself having to re-enable my favorite labs extensions multiple times a day, which is quite inconvenient and annoying. 
In this PR I've set the lab cookies to expire in 365 days instead of being session bound. I think this is going to make for a better experience and let users better customize their labs experience. Tested locally and seems to work as expected.
> Increase labs cookie expiry time

- browse/templates/abs/abs.html
- tests/test_bibex.py
This tag is redundant with the existing citation_doi tag that is suppose to get the jref DOI. That gets added in metatags.py.
The removed code sets it as the arXiv datacite DOI which is incorrect.
dev team ticket:
https://arxiv-org.atlassian.net/browse/ARXIVCE-264
Ops ticket:
https://arxiv-org.atlassian.net/browse/ARXIVOPS-2948
> Removes redundant `citation_doi` meta tag from head

- browse/static/js/inf-script.js
- browse/static/js/influenceflower.js
This pull request edits the description sentence of the influence flowers. Also, it fixes hyperlinks on flower nodes.
The sentence changes from 
> "Influence flowers are visualizations for citation influences among academic entities, including papers, authors, institutions, and research topics, computed using the Microsoft Academic Graph."
to
> "Influence flowers are visualizations for citation influences among academic entities, including papers, authors, institutions, and research topics. See [here](https://influencemap.cmlab.dev/) for more detail."
> edit description and fix href for influence flowers

- browse/templates/home/special-message.html
- browse/templates/user_banner.html
Ending forum banner early due to the high signup rate. Whenever this can be deployed to production that would be great. This PR includes a single line edit to user_banner.html, and also updates the homepage forum text.
> change banner end date

- browse/templates/home/home.html
Set URL to CS as CoRR to info.arxiv.org and set description to archive/cs.
These URLs are currently broken on the home page.
https://arxiv-org.atlassian.net/browse/ARXIVCE-285
> Fixes home page link for CS

- browse/templates/user_banner.html
Changed the end date to 04/09 (Sunday) which should hide the banner. This change can go live anytime. Steinn reports he is hearing grumbling from people annoyed at the banner presence, and we have enough attendees.
> take down forum banner

- browse/controllers/bibtexcite.py
- tests/test_bibex.py
/bibtex/None is throwing 500 when it should be 400. Fixes this and some other cases.
When InternalServerError is explicitly raised the stack trace of the error does not end up in the logs. That hinders investigation of problems. 
ARXIVCE-339
> Adds better error handling for /bibtex 

- browse/static/js/spaces.js
The new endpoint (e.g. https://huggingface.co/api/arxiv/1912.13318/repos) provides information of all spaces linked directly to a paper, hence avoiding doing two requests to the Hub to get the required information and simplifying the logic. On top of that, in the link to view all demos, it sorts by likes to give the most relevant ones
> Change Hugging Face integration to updated endpoint

- browse/controllers/abs_page/__init__.py
- browse/templates/abs/abs.html
- browse/templates/abs/extra_services.html
- tests/test_browse.py
Red boarder to black border. 
Withdrawn is not an error state. 
Removes download link to source ( https://arxiv.org/e-print/{arxiv_id} ) since there is not any source.
Bolds comment. Jim asked for a box similar to the withdrawn message but that doesn't work due tot he comment being in a table.
> Changes withdrawn abs page

- browse/templates/abs/abs.html
- tests/data/abs_files/ftp/astro-ph/papers/9709/9709175.abs
- tests/data/abs_files/orig/astro-ph/papers/9709/9709175v1.abs
- tests/data/abs_files/orig/astro-ph/papers/9709/9709175v2.abs
- tests/test_browse.py
Older submissions sometimes lack the submitter name. This is probably due to the early arxiv being email based and the submitter name being the optional name part of the from: email field.  
Compare newer abs file:
------------------------------------------------------------------------------
\\
arXiv:2101.10016
From: arXiv Admin <help@arxiv.org>
Date: Mon, 25 Jan 2021 11:32:05 GMT   (171kb)
To older abs file:
------------------------------------------------------------------------------
\\
arXiv:astro-ph/9709175
From: <ex@example.com>
Date: Wed, 17 Sep 1997 22:23:48 GMT   (130kb)
This fixes the code so it handles this unusual case. The display will look like this:
And a hover over info icon looks like this:
> Fixes bug with withdraw message on some older submissions

- browse/templates/home/home.html
- browse/templates/home/special-message.html
This PR removes some older references to news, and adds a permanent banner area on the homepage for notes of that kind.  This PR also adds a second, temporary banner area with a note about hiring and open roles. See screenshot:
> adds homepage news and hiring banner

- browse/static/css/arXiv.css
- browse/templates/base.html
adds minimal time-boxed banner to header with hiring link. It does not use our traditional banner code. This banner cannot be closed, but it also does not add to the header height or cover up any other content. It is set to stop displaying on August 1st, but this date can easily be adjusted.
Here are two color options for red-themed (current):
and blue-themed:
> Hiring banner

- browse/templates/abs/bookmarking.html
Removes 2 bookmark links. 
Mendeley was bought by elsevier and you are redirected to an Elsevier login page. That is a bad association for arXiv and not worth the small benefit to users of having that link on our page.
Sciencewise appears to not offer that service anymore, even on the new sciencewise.org.uk. Removing it for now, and if the service resurfaces we can add it back in.
> remove Mendeley and Sciencewise bookmark links from abs

- browse/templates/abs/extra_services.html
per https://arxiv-org.atlassian.net/browse/ARXIVCE-743
adjusts linking target on abstract pages to use their more straightforward url construction rather than a hook into their search.
> Updates INSPIRE HEP link target

- browse/commands/invalidate.py
- browse/config.py
- browse/factory.py
- browse/services/database/__init__.py
- poetry.lock
- pyproject.toml
Adds a flask cli command  in arxiv-browse as part of the flask app that invalidates PDF paths in the CDN. I did it as part of the flask app since I wanted access to the ORM models.
```
cloud_sql_proxy \
-instances=arxiv-somenv:us-regionN:arxiv-somenv-repN=tcp:0.0.0.0:1234 &
export BROWSE_SQLALCHEMY_DATABASE_URI=mysql://browse:{IN_SECRETS}@127.0.0.1:1234/arXiv
FLASK_APP=browse.factory:create_web_app flask invalidate invalidate_mailings -v 231009
About to query for 231009
For 231009 found 1230 papers.
2460 paths to invalidate. Two for each paper. One with version and one without.
/pdf/1010.2391.pdf
[... 600 or so lines ...]
/pdf/math/0607294.pdf
/pdf/math/0607294v3.pdf
Starting invalidation of paths in CDN.
Invalidated /pdf/1010.2391.pdf.
Invalidated /pdf/1010.2391v10.pdf.
Invalidated …
```
> Adds a flask cli command to invalidate PDF paths in the CDN

- browse/controllers/archive_page/__init__.py
- browse/controllers/response_headers.py
- tests/test_browse.py
Fixes duplicate Expires header
> Fix expires header

- .github/workflows/python-app.yml
- browse/commands/invalidate.py
Working on getting a python action that runs tests.
> moves tests inside poetry run in workflow

- script/sync_prod_to_gcp/sync_published_to_gcp.py
This:
1. decreases the concurrent per webnode /pdf  requests from 8 to 4 
2. adds retry to /pdf reqeusts 
3. adds retry to upload to GS
4. increases the wait time for a pdf to be built from 3 minutes to 5 minutes.
5. Adds a log msg on successful GET /pdf
Both retry's use the default settings: initial delay of 1 sec, max delay of 60 sec, multiplier of 2 and a timeout of 120 sec.  
The docs say timeout is "Timeout: the maximum duration of time after which a certain operation must terminate (successfully or with an error). The countdown begins right after an operation was started. For example, if an operation was started at 09:24:00 with timeout of 75 seconds, it must terminate no later than 09:25:15."
> Set /pdf requests per node 8 to 4, adds retry.

- browse/templates/base.html
- browse/templates/home/special-message.html
This PR adds two notices related to the open role for Production Editor: 
- A minimal banner in the header
- and a homepage block
Reviewers: please double check the start and end dates set for these banners to appear: 
if rd_int >= 202310120100 and rd_int <= 202311150100
so from 10/12 at 1:00am to 11/15 at 1:00am.
Also, please double check that the url I am linking to is the one we want to use: [workday job page](https://cornell.wd1.myworkdayjobs.com/en-US/CornellCareerPage/job/arXiv-Production-Editor--Cornell-Tech--NYC-_WDR-00040646)
See screenshot:
> adds minimal banner and homepage block for prod editor role

- browse/domain/metadata.py
- tests/test_fmt_txt.py
Jake pointed out that this was not the correct format.
ARXIVCE-701
> Adds breaks and abs to fmt=txt

- browse/templates/user_banner.html
This PR updates user_banner.html with the giving week banner content, and updates the display date range from Monday 10/23 through the end of the day of 10/29 (I set the end date to 10/30, is that right? or should it be 10/29?).
> adds giving week banner

- browse/controllers/home_page.py
- browse/templates/home/home.html
A DB query is made while creating our home page solely for the purpose of displaying the current article count, even though we only update the count once a day:
> open-access archive for 2,358,545 scholarly articles in the fields of physics
It turns out that this DB query is fairly expensive. And if anyone uses our home page as a health check, doing one such call per second adds significant load to the db-rep server -- practically a DDOS.
Changing this to a static string for now. Maybe later have this come from a file that we can update once a day after announce time.
> Remove DB call from home page

- browse/controllers/abs_page.py
- browse/domain/metadata.py
- browse/domain/version.py
- browse/services/dissemination/article_store.py
- browse/services/documents/db_implementation/db_abs.py
- browse/services/documents/fs_implementation/parse_abs.py
- browse/templates/abs/extra_services.html
- tests/test_fs_abs_parser.py
The db abs meatadata has the withdrawn status in arXiv_metadata.is_withdrawn and does not seem to indicate it with  source flag "I". 
This may be a divergence of how .abs files and db abs are recorded. This probably goes back to before 2013.
> Fixes bug with db_abs and withdrawn papers. ARXIVCE-960

- browse/controllers/abs_page.py
- browse/services/documents/db_implementation/convert.py
- browse/services/documents/db_implementation/db_abs.py
This was probably introduced recently.
The identifier object created by the controler is passed further down so it can be placed on the DocMeta object and then carries the info about the requested version. That is later picked up by the formats function.
> Early version of a wdr paper did not show download links

- browse/templates/base.html
- browse/templates/home/special-message.html
This PR adds a minimal header banner and a message block on the homepage linking to the annual brand perception survey. Screenshot is below showing both. 
They are set to display starting at 1:00AM on November 27th, until 1:00AM on November 29th. @cbf66 let's coordinate to make sure this window does not interfere with other planned dev update announcements.
We normally leave the banner up for only 24 hours. This year, I suspect we may need 48 hours to maintain a similar response rate as previous years, for two reasons:
- We are using a more minimal header banner, not the larger one that covers over the normal header. 
- the timing. Post-thanksgiving may get less engagement than previous years when we ran it in October.
> Deploying the annual survey via banner

- browse/static/js/litmaps.js
Our internal Litmaps ID system had changed, and the example arXiv paper link was lost in the shuffle.
> Update default example Litmaps article

- browse/controllers/year.py
- tests/test_hybrid_listing.py
temporary change to allow year to run while still working with legacy listings. The plan is to change this back once all of browse lsitings is in production
> changed urls to 2 digit years for CIT compatibility

- browse/controllers/years_operating.py
- tests/test_list_page.py
fixes a bug for archives that have end years where it would try and add a date and an int together
> years_operating now alwasy tries to add just the year of dates

- browse/static/css/arXiv.css
- browse/templates/abs/extra_services.html
This PR fixes a display issue when there is no license image, just a license link.
> fixes odd display when there is no license image

- browse/domain/identifier.py
- tests/test_browse.py
Adds handling of https://arxiv.org/abs/arxiv:ID that is used in old papers. 
This was part of the apache config pre-fastly.
https://arxiv-org.atlassian.net/browse/AH-86565
> Adds handling of ids like arxiv:astro-ph/011202 AH-86565

- browse/services/dissemination/article_store.py
Browse dropping the YYMM based gate for asking genpdf. genpdf can handle the "old" PDF by falling back to CIT. 
This is an unlikely situation, as the weekly cron job syncs up the CIT --> GCP. 
OTOH, genpdf is a bit more smart now.
> Browse can ask genpdf for pdf and no need to gate it by date anymore.

- browse/controllers/abs_page.py
- browse/controllers/response_headers.py
- browse/domain/identifier.py
- browse/services/database/__init__.py
- tests/test_304.py
- tests/test_db_abs.py
We lack a good record for all the data sources that makes up the /abs page so last-modified isn't working out.
Go to etag made from a hash of all the data used by the jinja html template.
> Change /abs to use etag instead of last-modified

- browse/controllers/__init__.py
- browse/controllers/files/__init__.py
- browse/controllers/files/ancillary_files.py
- browse/controllers/files/dissemination.py
- browse/services/next_published.py
- tests/dissemination/test_no_source.py
Sets `Cache-Control` to max-age of either 15 for un-versioned requests or 30 minutes for versioned requests.
Removes `Expires` header. This was based on the publish time and often was too far in the future to pick up changes like latexml or added DOIs.
> Changes file download caching

- browse/routes/dissemination.py
This creates a second path for PDF download only for use with testing fastly and genpdf.
Fastly can be left pointing /pdf to CIT and /pdf_test can be pointed at the cloud run arxiv-browse + genpdf.
> Adds /pdf_test path for testing fastly+genpdf

- browse/factory.py
- browse/routes/ui.py
- browse/templates/abs/bookmarking.html
Removes click through links.
Sets /ct to phase out in 2025 so as to not cause problems with any existing links.
> Removes click through links.

- browse/controllers/files/dissemination.py
Pass an `Iterator` instead of something duck typed as a open file.
Flask does nominal typing on inputs to `make_response()` so it rejects `BinaryMinimalFileTransformed`. It does accept an `Iterator` so just use that.
> Fixes problem with html conference proceedings

- browse/config.py
- browse/templates/abs/abs.html
- tests/test_doi.py
Removes `escape` since the DOI is transformed with urllib.parse.quote() which urlencodes < and >.
> Fixes DOI URLs with < or > on /abs arxivce-1373

- browse/controllers/files/dissemination.py
- browse/services/html_processing/__init__.py
- tests/test_html.py
The html_post_process fn subs in ABS and LIST in the html text for actual looked up abs metadata at time of request.
This was broken due to a recent change that moved it to after the app code so the fn was not in flask's request context. 
Calls `html_post_process` wrapped in `flask.stream_with_context` so it can access the metadata service even after the app code has returned.
Adds a test that should ensure that the `html_post_process` is not having errors due to this flask context problem
https://arxiv-org.atlassian.net/browse/AH-93375
> Fixes bug with conference proceedings

- browse/controllers/__init__.py
- browse/controllers/files/__init__.py
- browse/controllers/files/ancillary_files.py
`Requests` for versioned files get the max-age set to 7 days and unversioned requests for one day.
> Increases cache-control max age for files

- browse/controllers/abs_page.py
- tests/test_browse_links.py
collect context from article primary category when possible. Only use old style id archive as last resort.
Use canonical category names
> improve prev next context selection

- browse/templates/abs/extra_services.html
- tests/test_browse_links.py
switching this back to the old url schema while listings arent turned on
> switch abs link back to yymm which page change isnt deployed

- browse/controllers/list_page/__init__.py
- browse/routes/ui.py
- browse/templates/list/month.html
- browse/templates/list/year.html
- tests/listings/db/test_db_listing_month_year.py
- tests/listings/test_fake_list.py
- tests/listings/test_list_page.py
Potential pause to the 4 digit year url change until we are confident GCP listings will be kept up. There was a convenient place to bandaid the /list path but not the /year path so the plan would be just to deploy /list until we are confident it is good to go then we can revert this change and also deploy /year
Changed here:
-Band-Aid time period processing function that expects 2 digit years and never redirects
-use 2 digit urls to run listing tests
-skip the specific redirect test
-disable the url change alert
> Temp 2 digit year listings

- browse/controllers/__init__.py
- browse/controllers/list_page/__init__.py
- browse/routes/ui.py
- browse/services/listing/__init__.py
- tests/listings/test_list_page.py
fastly can use surrogate keys to purge specific sections of the cache
> Arxivce 1715 add surrogate key header to list

- browse/services/database/__init__.py
- tests/test_latexml_graceful.py
Adds a `ignore_errors` arg to `db_handle_error` decorator that we wrap many db calls with to have uniform error handling.
Sets `ignore_errors` to `True` on latexml DB calls. This should reduce cases where latexml DB down causes the service to error out.
This PR can be deployed immediately. An additional change in arxiv-base to handle the rollback is still needed to complete the graceful latexml DB down feature. It would be ideal if we could set arxiv-browse so it does not try to roll anything back since it is read only.
ARXIVCE-2433
> Graceful latexml DB down, part 1

- poetry.lock
- pyproject.toml
- tests/test_latexml_graceful.py
Removes pg8000 and uses psycopg2-binary due to the statement_timeout not working with pg8000.
> Uses arxiv-base with latexml db statement timeout

- browse/controllers/files/dissemination.py
- browse/routes/dissemination.py
- tests/dissemination/test_pdf.py
Adds Link header for /pdf that points to the versionless /pdf. 
The versioned /pdf URLs link to the versionless because we want the most recent version of the PDF to be the search link in search engine results. The versionless returns the most recent version of the PDF.
This also adds a redirect if the /pdf URL has any query string. While this is slightly against the google suggestions, we don't want folks to have to deal with crazy /pdf URLs from outside of arxiv.org.  
/abs already has canonical links in the HTML.
https://arxiv-org.atlassian.net/browse/ARXIVCE-63
https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls#rel-canonical-header-method
> Adds canonical link header for /pdf

- browse/templates/user_banner.html
Changed to:
<div><h3 style="text-align: center">🚨2024-09-29: <a href="https://https://status.arxiv.org">
arxiv.org is experience DB issues. The announce tonight will be 3 hours later than usual.</a>🚨
</h3></div>
Was pointing to blog post which prominently showed "arxiv is in read-only mode"
The status pages describes a 3h delay tonight.
> Change to outage banner

- browse/static/css/ar5iv_0.7.4.min.css
As I discovered today, `0.7.4` is hardcoded in early-2024 conversions, such as [this one](https://arxiv.org/html/2401.01544v1).
Returning it for a little while longer.
> Keep ar5iv_0.7.4.css asset until we regenerate all HTML

- browse/static/js/connectedpapers.js
- browse/templates/abs/labs_tabs.html
Following recent changes to the Connected Papers API, the integration got broken. This is a fix restoring the functionality.
In addition, looking over the various utilities, we have come to the conclusion connected papers fits better in the "Bibliographic and Citation Tools" tab
> Restore connected papers functionality and move to bibliographic tab

- browse/static/css/slider.css
- browse/templates/user_banner.html
shifted button placement right
previous button placement on large screen:
new button placement on large screen: 
new button placement on smallest screen:
> updated banner date/text

- browse/static/js/toggle-labs.js
- browse/templates/abs/labs_tabs.html
Moving to a bibex.js served by the arxiv-browse service, away from `static.arxiv.org`
In the interest of continuing the migration away from AWS, and more uniformity with the other Labs JS assets.
> use arxiv-browse asset for bibex.js

- browse/routes/ui.py
> ARXIVCE-2902 use first X-Forwarded-For IP in /institutional_banner

- browse/controllers/files/dissemination.py
- tests/dissemination/test_pdf.py
- tests/test_clickthrough.py
- tests/test_html.py
Changes:
1. Both bare and slashified `/html/` article routes now point to the same canonical URL
2. Adds a canonical URL for HTML articles via an HTTP Header, same approach as for `/pdf/`
3. Changes `/pdf/` canonical URLs to only use the version-less / latest URL.
> ARXIVCE-2997 versionless canonical URL for PDF and HTML articles

- browse/templates/base.html
The main switch is easy, if the HTML5 direction has strong support today.
There are other helpful [validator warnings and errors](https://validator.nu/?doc=https%3A%2F%2Farxiv.org), which could be addressed if there's interest.
> ARXIVCE-928 switch header from XHTML to HTML5

- browse/controllers/files/dissemination.py
Follow-up to #819 which had a routing oversight and only handled one of the HTML dissemination paths.
> ARXIVCE-2997 also set canonical URL header for latexml-based HTML assets

- browse/controllers/list_page/__init__.py
- browse/templates/list/list_macros.html
- tests/listings/db/test_db_listing.py
- tests/listings/db/test_db_listing_recent.py
- tests/listings/test_list_page.py
for the list pages only show values that our page specifies will be supported. This should discourage robots collecting the list pages at show=5 and help with cacheing
> reject custom show values

- browse/services/audio.py
- tests/test_audio.py
Per discussion with ScienceCast on 3/6, update the filter on our end to look for submissions with astro-HE as primary, announced since Dec 1 2024, and that are have tex source. 
Minor change from the ticket: it said ", and that are NOT pdf-only. " But I assumed sciencecast cannot handle other strange submissions. Also filtering out HTML, PS and DOCX.
> ScienceCast filter update

- browse/routes/ui.py
It appears that `no-store` was insufficient on its own. 
Now using more of the available cache control headers.
> ARXIVCE-3387 add no-cache, private, max-age and max-stale directives

- browse/controllers/files/dissemination.py
- browse/services/dissemination/article_store.py
Browse was asking genpdf for the PDF for papers with html source. This PR stops that.
This has nothing to do with the latexml HTML.
> Don't send html sourced papers to genpdf

- script/sync_prod_to_gcp/README.md
- script/sync_prod_to_gcp/resource/bin/arxiv-mail
- script/sync_prod_to_gcp/resource/bin/tex-compilation-problem-notification
- script/sync_prod_to_gcp/submissions_to_gcp.py
1. README has more instuctions about deployment
2. email and slack message sending scripts added to the resoures
3. Fixed the "error reported" marker file name to be abel to handle the old style arxiv ID
4. First default timeout is now 90 minutes instead of 60. It seems to routinely fall behind. This may be revisited once the s2g drives the PDF gen.
> sync-to-gcp to have better error messages

- script/sync_prod_to_gcp/Makefile
- script/sync_prod_to_gcp/submissions-to-gcp.sh
- script/sync_prod_to_gcp/submissions_to_gcp.py
- script/sync_prod_to_gcp/sync_published_to_gcp.py
web7 out of rotation.
Notification timeouts is longer. First timeout is now 3h.
> sync-to-gcp upload to use md5

- script/sync_prod_to_gcp/sync_published_to_gcp.py
This forces the GS lib to use HEAD instead of GET which is likely more "up-to-date".
> plain get_blob() seems to not work quite right sometimes

- browse/templates/cookies.html
This PR adds code for opt-in/opt-out on the cookies.html page.
This page was created by Deyan. I simply replaced a call to backend Cloud Function with generating a UUID on the page itself.
This decision may be revisited in the future.
The goal of this PR is to get something deployed so that we are able to start collecting preliminary log data.
I have created a separate ticket to review the content of the new Opt-In text [Review Opt-In Text](https://arxiv-org.atlassian.net/browse/ARXIVCE-3807).
Current Opt-In Browse Page:
> ARXIVCE-3802: Simplified code to set cookie from page (via Deyan)

- browse/controllers/list_page/author.py
- browse/formatting/metatags.py
- browse/routes/dissemination.py
- tests/data/classic_scholar_metadata_tags.json
- tests/dissemination/test_pdf.py
The bug was that a URL like https://arxiv.org/pdf/2501.12345.pdf would redirect to http://arxiv.org/pdf/2501.12345. Note the https is chagned to http and the trailing .pdf is removed. The chagne from https to http is the bug. This commit fixes that bug.
Changes the abs HTML metadata pdf URL from a http to https.
Changes the author list page pdf URL from a http to https.
> Fixes pdf redirect to http bug ARXIVCE-2718

- browse/static/css/arXiv.css
- browse/static/js/optin.js
- browse/templates/base.html
- browse/templates/home/home.html
- browse/templates/opt_in_button.html
- browse/templates/user_banner.html
This PR includes a lot of code cleanup and changes to control the display states of the banner and new status button. This PR adds a "placeholder" button to represent the status of the opt-in feature. This was not designed or specified in the OptIn banner mockup document. This new 'status' button is intended to present the state of the opt-in feature and allow the user to change the state after the banner is hidden (once the user makes a choice).
This PR is necessary to deploy these changes to the browse.dev.arxiv.org server.
I still need to make adjustments to the button. The mockup document contains 'for discussion' bullet points for how to present this information on an arXiv page. The design of this status 'feature' needs to be discussed by stakeholders.
Once this is approved I will …
> ARXIVCE-3884 Opt in banner refinements - add new status button

- browse/static/css/arxiv-html-papers-theme-20250916.css
This PR redoes the black-to-dark-mode fixed map from [ar5iv.0.8.4css here](https://github.com/arXiv/arxiv-browse/blob/318f0aee0ef7052dc943607867323ada35538d8c/browse/static/css/ar5iv.0.8.4.css#L147-L153) using the warm wash arXiv foreground color.
Also a decent example where a "design token" --var name could have avoided the duplication of the selector rule. For now simply adjust the obvious way - this rule is used surprisingly often, as there are millions of black (`#000000`) inline color annotations coming from `\color{black}` in the source files.
For comparison see the text before/after Introduction at https://arxiv.org/html/2402.17214v2#S1
> [HTML25-165] use arxiv foreground color for black-to-dark-mode map

- browse/templates/cookies.html
Minor update to Opt-In text on cookie.html page that removes "...No other researchers or institutions will have access to this data..." from earlier version.
We are still waiting for final version of this text.
> ARXIVCE-3976: Update opt-in text on cookies.html page to newer draft.
